version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: practicacomplexivodb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: basecomplexivo
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - net-cloud

  productoservice-api:
    image: franklinorellana/productoservice-api:1.0
    container_name: productoserviceapi
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/basecomplexivo?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: debug
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "9898:9898"
    restart: always
    networks:
      - net-cloud

networks:
  net-cloud:

volumes:
  mysql-data:
